name: aramex
description: A new Flutter project.

version: 0.0.6+6

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ui  widgets
  cupertino_icons: ^1.0.5
  pin_code_fields: ^7.4.0
  dotted_border: ^2.0.0+3
  flutter_svg: ^2.0.6
  dotted_line: ^3.1.0
  sliver_tools: ^0.2.10
  iconsax: ^0.0.8
  boxy: ^2.0.9
  syncfusion_flutter_charts: ^21.2.6
  page_transition: ^2.0.9
  animations: ^2.0.5
  loading_overlay: ^0.3.0
  jiffy: ^5.0.0

  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  shimmer: ^3.0.0

  # other utils
  equatable: ^2.0.5
  google_api_availability: ^5.0.0
  package_info_plus: ^4.0.1
  image_picker: ^0.8.7+5

  # state management
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  rxdart: ^0.27.7
  logger:

  # network
  dio: ^5.1.2
  connectivity_plus: ^4.0.1
  fk_user_agent: ^2.1.0

  # data persistence
  shared_preferences: ^2.1.1

  # localization
  easy_localization: ^3.0.2

  #Firebase
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/aramex.png"
  min_sdk_android: 21

flutter:
  assets:
    - assets/translations/
    - assets/images/

  uses-material-design: true

  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900
    - family: QuickSand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: Aramex
      fonts:
        - asset: assets/fonts/Aramex.ttf
