name: aramex
description: A new Flutter project.

version: 0.0.3+3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ui  widgets
  cupertino_icons: ^1.0.4
  pin_code_fields: ^7.4.0
  dotted_border: ^2.0.0+2
  flutter_svg: ^1.0.3
  dotted_line: ^3.1.0
  sliver_tools: ^0.2.8
  iconsax: ^0.0.8
  boxy: ^2.0.6+2
  syncfusion_flutter_charts: ^20.2.50
  page_transition: ^2.0.9
  animations: ^2.0.5
  loading_overlay: ^0.3.0
  jiffy: ^5.0.0

  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  shimmer: ^2.0.0

  # other utils
  social_share: ^2.3.1
  equatable: ^2.0.3
  google_api_availability: ^3.0.1
  package_info_plus: ^1.4.3+1
  image_picker: ^0.8.6

  # state management
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0
  rxdart: ^0.26.0
  logger:

  # network
  dio: ^4.0.6
  connectivity_plus: ^2.2.1
  fk_user_agent: ^2.1.0

  #Social Login
  flutter_facebook_auth: ^4.1.2
  google_sign_in: ^5.2.4

  # data persistence
  shared_preferences: ^2.0.15

  # localization
  easy_localization: ^3.0.0

  #Firebase
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/aramex.png"
  min_sdk_android: 21

flutter:
  assets:
    - assets/translations/
    - assets/images/

  uses-material-design: true

  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900
    - family: QuickSand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: Aramex
      fonts:
        - asset: assets/fonts/Aramex.ttf
