/// Flutter icons Aramex
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Aramex
///      fonts:
///       - asset: fonts/Aramex.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Aramex {
  Aramex._();

  static const _kFontFam = 'Aramex';
  static const String? _kFontPkg = null;

  static const IconData arrowright = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codcollected = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codpaid = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emptywallet = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codshipment = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moneyrecive = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moneys = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pdf = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walletadd = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xf0b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
