/// Flutter icons Aramex
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Aramex
///      fonts:
///       - asset: fonts/Aramex.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Aramex {
  Aramex._();

  static const _kFontFam = 'Aramex';
  static const String? _kFontPkg = null;

  static const IconData codshipment = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pdf = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codcollected = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codpaid = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
